import { z } from "zod";

export const userSchema = z.object({
  categories: z.array(z.string()),
  upvotedManga: z.array(z.string()),
  heartedManga: z.array(z.string()),
  commentedManga: z.array(z.string()),
  followedUsers: z.array(z.string()),
  paid: z.boolean(),
  userID: z.string(),
  username: z.string(),
  email: z.string().email(),
  bio: z.string(),
  profileimage: z.string().url(),
  coverImage: z.string().url(),
  isAuthorisedForTesting: z.boolean(),
  emailVerificationAfterLoginSent: z.boolean(),
  dateOfFirstLogin: z.string(),
  dateOfAuthorisation: z.string(),
  credits: z.number().int(),
  plan: z.string(),
  extra_credits: z.number().int(),
  plan_buy_time: z.string(),
  daily_award_taken: z.boolean(),
  award_taken_time: z.string(),
  login_times: z.number().int(),
  last_login_time: z.string(),
  last_logout_time: z.string(),
  login_history: z.array(z.string()),
});
